### ISSUE TITLE
[建议] *.iml 配置文件不要 gitignore

### ISSUE THREAD

**Issue by fashare2015** [pengwei1024/AndroidSourceViewer#1]
首先，体验了一把插件。只想说，厉害了我的哥！
然后，clone 了一下源码，发现 run 不起来。

发现原来是配置文件 .iml 被 ignore 了。
里面有 `IDEA SDK`, `META-INF/plugin.xml`, `src`, `resources`等路径的配置，建议用 git 托管。

**Comment by pengwei1024** [comment]
直接导入插件会被解析为 Java 项目，改下*.iml 里面的 `module type="JAVA_MODULE"` 改成 `module type="PLUGIN_MODULE"` 应该就好了 [http://www.apkfuns.com/-e5-af-bc-e5-85-a5intellij-plugin-e9-a1-b9-e7-9b-ae-e6-8a-a5-e9-94-99no-plugin-module-specified-for-configuration/](http://www.apkfuns.com/-e5-af-bc-e5-85-a5intellij-plugin-e9-a1-b9-e7-9b-ae-e6-8a-a5-e9-94-99no-plugin-module-specified-for-configuration/)  Android 中忽略*.iml习惯了 ![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/34/xiaoku_thumb.gif)，你的建议我会考虑下，多谢反馈

**Comment by fashare2015** [comment]
恩，这个坑我知道，简直巨坑。

但不只这个，`*.iml`和`.gradle`有点像，里边还有第三方库的依赖。所以我这边clone下来，java代码中有一些import找不到。不确定你是否用了其他第三方库。

或者你可以尝试用 gradle 构建，还TM能用 kotlin 写。
https://github.com/JetBrains/gradle-intellij-plugin/tree/master/examples

**Comment by pengwei1024** [comment]
那我知道啥原因了，应该是我依赖了 Android.jar, 用了里面的 FileUtil。可以改成 gradle 的

**Comment by fashare2015** [comment]
话说回来，还是挺牛逼的。我`Diff`了一下Android5.0和6.0的Activity，很直观的看到了6.0关于动态权限的变化。
>期待插件越来越好！！！
