### ISSUE TITLE
error download

### ISSUE THREAD

**Issue by xfhy** [pengwei1024/AndroidSourceViewer#14]
error download,老铁,下载源码总是会失败

**Comment by xfhy** [comment]
无法跳转到官方文档了,,不管什么方法都会打开https://developer.android.google.cn/reference/,这个地址

**Comment by minminaya** [comment]
Error: Download android.os.StrictMode.VmPolicy.Builder Failure

**Comment by pengwei1024** [comment]
sorry，下载地址服务器出现了问题。我现在已经修复，欢迎你们再试试。等忙完这段时间，我有计划对这个插件进行更新，加入更多实用功能，欢迎提交pr

**Comment by xfhy** [comment]
谢谢,辛苦啦
