### ISSUE TITLE
点击安装超时，下载链接也一直加载不出来

### ISSUE THREAD

**Issue by scucheri** [pengwei1024/AndroidSourceViewer#17]

**Comment by pengwei1024** [comment]
https://github.com/pengwei1024/AndroidSourceViewer/blob/master/jar/AndroidSourceViewer-1.0.2.jar?raw=true  点击这个链接下载呢？

**Comment by scucheri** [comment]
https://plugins.jetbrains.com/plugin/10187-androidsourceviewer 
这个后来出来了，现在可用，谢谢哦

**Comment by pengwei1024** [comment]
不用客气
