### ISSUE TITLE
我这边为啥不行

### ISSUE THREAD

**Issue by xinledanding** [pengwei1024/AndroidSourceViewer#2]
Activity 我点击到这个类 然后下载下来的时候 是RemoteGrantedReceiver 这个类 ,我是通过jar包导入的 ,从android studio的插件页面查询不到

**Comment by pengwei1024** [comment]
不好意思插件审核还没有通过![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2c/moren_yunbei_thumb.png) 之前都是审核特别快的。请问是必现吗？具体选中的元素是哪个呢？

**Comment by Hansnowqiang** [comment]
macos+as3.0 点击直接调起了chrome，什么都没有。。。

**Comment by pengwei1024** [comment]
@Hansnowqiang 是选择的`Android Developer Viewer`吗？这个会打开官方文档，如[https://developer.android.google.cn/reference/android/app/Activity.html#onPostCreate(android.os.Bundle) ](https://developer.android.google.cn/reference/android/app/Activity.html#onPostCreate(android.os.Bundle)) 这个不知道是 chrome 的问题还是啥？我也遇到过，重启 chrome 就好了
