### ISSUE TITLE
http://androidxref.com 访问不了

### ISSUE THREAD

**Issue by android-xiaowei** [pengwei1024/AndroidSourceViewer#3]
http://androidxref.com 访问不了

**Comment by pengwei1024** [comment]
是啊，我也很绝望，看有没有更靠谱的源码地址以后换了，[http://grepcode.com/](http://grepcode.com/) 数据比较旧

**Comment by panshen** [comment]
同样访问不了

**Comment by pengwei1024** [comment]
@panshen 只能等美国天亮后恢复了![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2c/moren_yunbei_thumb.png)

**Comment by pengwei1024** [comment]
@android-xiaowei @panshen 1.0.2版本已经支持在androidxref不稳定时候切换 android.googlesource.com 欢迎试用[https://github.com/pengwei1024/AndroidSourceViewer/tree/master/jar](https://github.com/pengwei1024/AndroidSourceViewer/tree/master/jar)

**Comment by panshen** [comment]
可以了 感谢！ @pengwei1024
