### ISSUE TITLE
AndroidSourceViewer threw an uncaught NoClassDefFoundError.

### ISSUE THREAD

**Issue by iluhcm** [pengwei1024/AndroidSourceViewer#6]
Env 
HW: MacBook Pro (Retina, 15-inch, Mid 2015)
OS: macOS Sierra, 10.12.5
Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by pengwei1024** [comment]
试试 1.0.2版本？看看是不是用了 TextUtil 导致的 [https://github.com/pengwei1024/AndroidSourceViewer/tree/master/jar](https://github.com/pengwei1024/AndroidSourceViewer/tree/master/jar)

**Comment by iluhcm** [comment]
1.0.2可以了，谢谢。
